name: K6 Aggregate Consistency Test

on:
  workflow_dispatch:
  schedule:
    - cron: "30 19 * * 1,5"

jobs:
  aggregate_logic_test:
    name: Run Aggregate Test
    runs-on:
      labels: moj-cloud-platform

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25"

      - name: Build xk6 dashboard-enabled k6
        run: |
          go install go.k6.io/xk6/cmd/xk6@latest
          xk6 build --with github.com/grafana/xk6-dashboard@latest

      - name: Run k6 Aggregate Test
        env:
          AAP_CLIENT_ID: ${{ secrets.AAP_CLIENT_ID }}
          AAP_CLIENT_SECRET: ${{ secrets.AAP_CLIENT_SECRET }}
          TOKEN_URL: ${{ secrets.TOKEN_URL }}

          MIN_THINK_TIME: "1"
          MAX_THINK_TIME: "5"
          
          VUS: "1"
          DURATION: "5m"

          P95_THRESHOLD: "600" 
          P90_THRESHOLD: "400"
          
        run: ./k6 run performance/tests/aapAggregate.js --out web-dashboard=export=aap-aggregate-report.html

      - name: Upload Aggregate Report
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: k6-aggregate-report
          path: aap-aggregate-report.html
          retention-days: 1