name: Playwright Tests
on:
  workflow_call:
    inputs:
      channel_id:
        description: 'The slack channel ID to send a message on failure. If this is not provided then no message is sent.'
        required: false
        default: 'NO_SLACK'
        type: string

jobs:
  test:
    timeout-minutes: 60
    runs-on:
      labels: moj-cloud-platform
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright
        run: npx playwright install
      - name: Run Playwright tests
        id: playwright-tests
        run: npx playwright test --project=chromium
        env:
          ORACLE_DB_USER: ${{ secrets.ORACLE_DB_USER }}
          ORACLE_DB_PASSWORD: ${{ secrets.ORACLE_DB_PASSWORD }}
          ORACLE_DB_CONNECT_STRING: ${{ secrets.ORACLE_DB_CONNECT_STRING }}
          SP_CLIENT_ID: ${{ secrets.SP_CLIENT_ID }}
          SP_CLIENT_SECRET: ${{ secrets.SP_CLIENT_SECRET }}
          AAP_CLIENT_ID: ${{ secrets.AAP_CLIENT_ID }}
          AAP_CLIENT_SECRET: ${{ secrets.AAP_CLIENT_SECRET }}
          # URLs
          DELIUS_URL: https://ndelius.test.probation.service.justice.gov.uk
          TOKEN_URL: ${{ secrets.TOKEN_URL }}
          # Credentials
          DELIUS_USERNAME: ${{ secrets.E2E_DELIUS_USERNAME }}
          DELIUS_PASSWORD: ${{ secrets.E2E_DELIUS_PASSWORD }}
        
      - name: Install k6
        uses: grafana/setup-k6-action@v1

      - name: Run k6 performance test
        run: k6 run performance/tests/aapApi.js
          
      - name: Slack notification
        if: failure() && inputs.channel_id != 'NO_SLACK'
        uses: ./.github/actions/slack_integration_notification
        with:
          title: "Integration tests notification"
          channel_id: ${{ inputs.channel_id }}
          SLACK_BOT_TOKEN: ${{ secrets.HMPPS_SLACK_BOT_TOKEN }}
